(define (problem bridges)
 (:domain Bridges)
 (:init
  (at_0_0)
  (valid)
  (probabilistic 0.5 (openprec_move_0_0_1_0_bridge_0_0_1_0))
  (probabilistic 0.5 (openprec_move_1_0_0_0_bridge_0_0_1_0))
 )
 (:goal (and (done)))
)
