(define (problem strips-gripper4)
  (:domain gripper-strips)
  (:objects rooma roomb ball1 ball2 ball3 ball4 left right)
  (:init (room rooma)
	 (room roomb)
	 (ball ball1)
	 (ball ball2)
	 (ball ball3)
	 (ball ball4)
	 (gripper left)
	 (gripper right)
	 (at_robby rooma)
;	 (free left)
;	 (free right)
	 (atb ball1 rooma)
	 (atb ball2 rooma)
	 (atb ball3 rooma)
	 (atb ball4 rooma))
  (:goal (and (atb ball1 roomb)
	      (atb ball2 roomb)
	      (atb ball3 roomb))))
