(define (problem GROUNDED-PATHWAYS-01)
 (:domain GROUNDED-PATHWAYS-PROPOSITIONAL)
 (:init
  (not-chosen_e2f13)
  (not-chosen_p130-e2f5p1-dp12)
  (num-subs_l0)
  (not-chosen_p16)
  (not-chosen_prbp2)
  (not-chosen_chk1)
  (not-chosen_raf1)
  (not-chosen_cdc25c)
  (not-chosen_cdk46p3-cycdp1)
  (not-chosen_ap2)
  (not-chosen_dmp1)
  (not-chosen_p300)
  (not-chosen_cdk7)
  (not-chosen_cdk46p3-cycd)
  (not-chosen_pcaf)
  (not-chosen_prb-e2f4p1-dp12)
  (not-chosen_sp1)
  (valid)
  (probabilistic 0.5 (openprec_ASSOCIATE-WITH-CATALYZE_DMP1_CDK46P3-CYCD_DMP1P1_available_cdk46p3-cycd))
  (probabilistic 0.5 (openprec_ASSOCIATE-WITH-CATALYZE_PRBP2_CDK46P3-CYCDP1_PRBP1P2_available_cdk46p3-cycdp1))
  (probabilistic 0.5 (possclob_ASSOCIATE-WITH-CATALYZE_PRBP2_CDK46P3-CYCDP1_PRBP1P2_available_prbp2))
  (probabilistic 0.5 (openprec_ASSOCIATE-WITH-CATALYZE_PRBP2_CDK46P3-CYCD_PRBP1P2_available_cdk46p3-cycd))
  (probabilistic 0.5 (unlistedeffect_ASSOCIATE_PCAF_P300_PCAF-P300_available_pcaf-p300))
  (probabilistic 0.5 (possclob_ASSOCIATE_PCAF_P300_PCAF-P300_available_pcaf))
  (probabilistic 0.5 (possclob_ASSOCIATE_PCAF_P300_PCAF-P300_available_p300))
 )
 (:goal (and (done)))
)
