(define (problem GROUNDED-PATHWAYS-05)
 (:domain GROUNDED-PATHWAYS-PROPOSITIONAL)
 (:init
  (not-chosen_ge2)
  (not-chosen_e2f5-dp12p1)
  (num-subs_l0)
  (not-chosen_p16)
  (not-chosen_e2f1)
  (not-chosen_cks1)
  (not-chosen_cdk46p1)
  (not-chosen_e2f2)
  (not-chosen_e2f13-dp12)
  (not-chosen_e2f13p1-dp12p1)
  (not-chosen_dp12)
  (not-chosen_e2f5)
  (not-chosen_e2f6)
  (not-chosen_hdac1-prbp1-e2f4-dp12)
  (not-chosen_p53)
  (not-chosen_pcna)
  (not-chosen_cdk2)
  (not-chosen_cdk1p1p2)
  (not-chosen_jun)
  (not-chosen_cdk2p1)
  (not-chosen_p130)
  (not-chosen_gercc1)
  (not-chosen_sp1)
  (valid)
  (probabilistic 0.5 (unlistedeffect_SYNTHESIZE_P53_GADD45_available_gadd45))
 )
 (:goal (and (done)))
)
