(define (problem GROUNDED-PATHWAYS-09)
 (:domain GROUNDED-PATHWAYS-PROPOSITIONAL)
 (:init
  (not-chosen_e2f13-dp12p1)
  (not-chosen_c-tak1)
  (not-chosen_ge-c)
  (not-chosen_p16)
  (not-chosen_e2f13p1-dp12)
  (not-chosen_cdc25c)
  (not-chosen_c-abl)
  (not-chosen_plk1)
  (not-chosen_prb)
  (not-chosen_cdk1p1p2)
  (not-chosen_apc)
  (not-chosen_sl1)
  (not-chosen_prbp1-e2f4p1-dp12)
  (not-chosen_prbp2)
  (not-chosen_cks1)
  (not-chosen_raf1)
  (not-chosen_cdk46p3-cycdp1)
  (not-chosen_cycb)
  (not-chosen_m1433)
  (not-chosen_cych)
  (not-chosen_cdk7)
  (not-chosen_cebp)
  (not-chosen_hdac1)
  (not-chosen_p130-e2f5p1-dp12)
  (num-subs_l0)
  (not-chosen_cdk46p1)
  (not-chosen_p130-e2f4p1-dp12)
  (not-chosen_e2f13p1-dp12p1)
  (not-chosen_ap2)
  (not-chosen_pcna)
  (not-chosen_cdk2-cycb)
  (not-chosen_hbp1)
  (not-chosen_cdk46p3-cycd)
  (not-chosen_wee1)
  (not-chosen_e2f1)
  (not-chosen_e2f13-dp12)
  (not-chosen_e2f2)
  (not-chosen_dp12)
  (not-chosen_e2f3)
  (not-chosen_e2f4)
  (not-chosen_e2f5)
  (not-chosen_e2f6)
  (not-chosen_p53)
  (not-chosen_cdk2p2-cycb)
  (not-chosen_myt1)
  (not-chosen_cdk2)
  (not-chosen_jun)
  (not-chosen_cdk2p1)
  (not-chosen_p130)
  (valid)
  (probabilistic 0.5 (possclob_ASSOCIATE-WITH-CATALYZE_CDK1P1P3-CYCB_CDC25CP1P2_CDK1P3-CYCB_available_cdk1p1p3-cycb))
  (probabilistic 0.5 (possclob_ASSOCIATE-WITH-CATALYZE_CDK7-CYCH_CDK7-CYCH_CDK7P1-CYCH_available_cdk7-cych))
  (probabilistic 0.5 (unlistedeffect_ASSOCIATE_E2F2_DP12_E2F2-DP12_available_e2f2-dp12))
  (probabilistic 0.5 (possclob_ASSOCIATE_E2F2_DP12_E2F2-DP12_available_e2f2))
  (probabilistic 0.5 (possclob_ASSOCIATE_E2F2_DP12_E2F2-DP12_available_dp12))
 )
 (:goal (and (done)))
)
