(define (problem GROUNDED-PATHWAYS-01)
 (:domain GROUNDED-PATHWAYS-PROPOSITIONAL)
 (:init
  (not-chosen_e2f13)
  (not-chosen_p130-e2f5p1-dp12)
  (num-subs_l0)
  (not-chosen_p16)
  (not-chosen_prbp2)
  (not-chosen_chk1)
  (not-chosen_raf1)
  (not-chosen_cdc25c)
  (not-chosen_cdk46p3-cycdp1)
  (not-chosen_ap2)
  (not-chosen_dmp1)
  (not-chosen_p300)
  (not-chosen_cdk7)
  (not-chosen_cdk46p3-cycd)
  (not-chosen_pcaf)
  (not-chosen_prb-e2f4p1-dp12)
  (not-chosen_sp1)
  (valid)
  (cpt (possclob_ASSOCIATE-WITH-CATALYZE_CDC25C_CHK1_CDC25CP2_available_cdc25c) 0.5)
  (cpt (possclob_ASSOCIATE-WITH-CATALYZE_DMP1_CDK46P3-CYCDP1_DMP1P1_available_dmp1) 0.5)
  (cpt (openprec_ASSOCIATE-WITH-CATALYZE_PRBP2_CDK46P3-CYCD_PRBP1P2_available_cdk46p3-cycd) 0.5)
 )
 (:goal 0.000001
 (and (done)))
)
