(define (domain mable-control)
 (:predicates
   (LESSON ?l)
   (TEMPLATE ?t)
   (NIMDIMENSION ?n) ;nimDimension 
   (TARGETCONCEPT ?tc)
   (TARGETCONCEPTTYPECODE ?tc)
   (TARGETCONCEPTTYPESYNTAX ?tc)
   (STRATEGY ?s)
   (CODE ?c)
   (SYNTAX ?s)
   (CONCEPTDIMENSION ?c)
   
   (newDefCode ?c)
   (newDefSyntax ?s)
   (defCodeForTarget ?c ?tc)
   (defSyntaxForTarget ?s ?tc)
   (priorDefCodeForTarget ?c ?tc)
   (priorDefSyntaxForTarget ?s ?tc)
   (interpretationForTarget ?c ?tc) ;;earmarked, but unlearned interpretation for target

   (lessonNIMDIMENSION ?l ?n)
   (targetCONCEPTDIMENSION ?tc ?d)
   (strategyNIMDIMENSION ?s ?n)
   (strategyCONCEPTDIMENSION ?c ?n)
   (lessonMessagesInTemplate ?l ?t)
   (templateHasLesson ?t)
 
   (nimDimensionInTemplate ?n ?t)
   (conceptDimensionInTemplate ?c ?t)
   (targetInTemplate ?tc ?t)
   
 
   (templateHasNIMDIMENSION ?t)
   (templateHasCONCEPTDIMENSION ?t)
   
   (composedOf ?tc ?tc1)
   (learnedCode ?tc)
   (learnedSyntax ?tc)
   (newlyLearnedCode ?tc)
   (newlyLearnedSyntax ?tc)
 
   (templateHasTarget ?t)
   (templateComplete ?t)
   (templateHasNoNIMDIMENSION ?t)
   (templateHasNoCONCEPTDIMENSION ?t)
   (codeStrategy ?s)
   (syntaxStrategy ?s)
   (untried ?s ?tc ?nim ?cd) ;;indicates if tried strategy on target !!Not contextual, need to generalize!!
 )
  
   
  (:action checkPrerequisitesLearned
   :parameters (?tc)
   :precondition (and (TARGETCONCEPT ?tc)
                      (forall (?tc1) 
                              (implies (composedOf ?tc ?tc1) 
                                       (learned ?tc)))
                              )
                      ) 
   				 )
   :effect (and (havePrerequisiteCIs ?tc))
  )
  
  (:action invokeCodeStrategyOnTemplate
   :parameters (?s ?t ?n ?cd ?c ?tc ?sc)
   :precondition (and (STRATEGY ?s)
   					  (TEMPLATE ?t)
   					  (NIMDIMENSION ?n)
   					  (CONCEPTDIMENSION ?cd)
   					  (TARGETCONCEPT ?tc)
   					  ;;(TARGETCONCEPTTYPECODE ?tc)
   					  (SYNTAX ?sc)
   					  (CODE ?c)
   					  (codeStrategy ?s)					  
   					  ;;(templateComplete ?t)
   					  (interpretationForTarget ?c ?tc)
   					  (nimDimensionInTemplate ?n ?t)
   					  (strategyNIMDIMENSION ?s ?n)
   					  (conceptDimensionInTemplate ?cd ?t)
   					  (strategyCONCEPTDIMENSION ?s ?cd)
   					  ;(newDefCode ?c)
   					  ;(defSyntaxForTarget ?sc ?tc)
   					  ;(learnedSyntax ?tc) 
   					  (untried ?s ?tc ?n ?cd)
   					  (targetInTemplate ?tc ?t)  	
   					  (havePrerequisiteCIs ?tc)				     					  
   					  )
   :effect (and (not (untried ?s ?tc ?n ?cd)))
   :poss-effect (and (defCodeForTarget ?c ?tc)
   				;(not (newDefCode ?c))
   				)
   )
   
   (:action invokeSyntaxStrategyOnTemplate
   :parameters (?s ?t ?n ?cd ?c ?tc)
   :precondition (and (STRATEGY ?s)
   					  (TEMPLATE ?t)
   					  (NIMDIMENSION ?n)
   					  (CONCEPTDIMENSION ?cd)
   					  (SYNTAX ?c) ;;
   					  (TARGETCONCEPT ?tc)
   					  ;;(TARGETCONCEPTTYPESYNTAX ?tc)
   					  (syntaxStrategy ?s)
   					  ;;(templateComplete ?t)
   					  (interpretationForTarget ?c ?tc)
   					  (nimDimensionInTemplate ?n ?t)
   					  (strategyNIMDIMENSION ?s ?n)
   					  (conceptDimensionInTemplate ?cd ?t)
  					  (strategyCONCEPTDIMENSION ?s ?cd)
   					  ;(newDefSyntax ?c)
   					  (untried ?s ?tc ?n ?cd)
   					  (targetInTemplate ?tc ?t)
   					  )
   :effect (and (not (untried ?s ?tc ?n ?cd)))
   :poss-effect (and (defSyntaxForTarget ?c ?tc)
   				;(not (newDefSyntax ?c))
   				)
   )

   (:action invokeSyntaxAndCodeStrategyOnTemplate
   :parameters (?s ?t ?n ?cd ?c1 ?c2 ?tc)
   :precondition (and (STRATEGY ?s)
   					  (TEMPLATE ?t)
   					  (NIMDIMENSION ?n)
   					  (CONCEPTDIMENSION ?cd)
   					  (SYNTAX ?c1) 
   					  (CODE ?c2)
   					  (TARGETCONCEPT ?tc)
   					  (syntaxStrategy ?s)
   					  (codeStrategy ?s)			  
   					  (nimDimensionInTemplate ?n ?t)
   					  (strategyNIMDIMENSION ?s ?n)
   					  (interpretationForTarget ?c1 ?tc)
   					  (interpretationForTarget ?c2 ?tc)
   					  (conceptDimensionInTemplate ?cd ?t)
  					  (strategyCONCEPTDIMENSION ?s ?cd)
   					  ;(newDefSyntax ?c1)
   					  ;(newDefCode ?c2)
   					  (untried ?s ?tc ?n ?cd)
   					  (targetInTemplate ?tc ?t)
   					  )
   :effect (and (not (untried ?s ?tc ?n ?cd)))
   :poss-effect (and (defSyntaxForTarget ?c1 ?tc)
   				;(not (newDefSyntax ?c1))
   				(defCodeForTarget ?c2 ?tc)
   				;(not (newDefCode ?c2))
   				)
   )
   
   (:action reusePriorCode
    :parameters (?tc ?c)
    :precondition (and  (TARGETCONCEPT ?tc)
    					(priorDefCodeForTarget ?c ?tc)
 				   )
 	:effect (and )
    :poss-effect (and (learnedCode ?tc))
   )

   (:action reusePriorSyntax
    :parameters (?tc ?c)
    :precondition (and  (TARGETCONCEPT ?tc)
    					(priorDefSyntaxForTarget ?c ?tc)
 				   )
 	:effect (and )
    :poss-effect (and (learnedSyntax ?tc))
   )

   
   (:action satisfyCodeTarget
    :parameters (?tc ?c)
    :precondition (and  (TARGETCONCEPT ?tc)
    					(CODE ?c)
    					(interpretationForTarget ?c ?tc)
    					(defCodeForTarget ?c ?tc))
    :effect (and (newlyLearnedCode ?tc) 
    			 (learnedCode ?tc))
   )

   (:action satisfySyntaxTarget
    :parameters (?tc ?c)
    :precondition (and  (TARGETCONCEPT ?tc)
    					(SYNTAX ?c)
    					(interpretationForTarget ?c ?tc)
 						(defSyntaxForTarget ?c ?tc))
    :effect (and (newlyLearnedSyntax ?tc)
    			 (learnedSyntax ?tc))
   )

)
