 (define (problem TBDName)
 (:domain mable-control)
(:objects 
   t3 t2 t1 t0 t4 t5 - template
   ExpandNodes-syntax - syntaxtarget
   ByDefinition ConditionWhenToCalculate ConditionEffectsOf HowToDo ConditionWhenTrue HowToCalculate DefinitionOf ConditionWhenToDo - conceptdimension
   PredicatesByFeedbackStrategy EBEByFeedbackStrategy EBELearningStrategy FunctionsByFeedbackStrategy ExampleOfProcedureStrategy ProcedureByFeedbackStrategy TellingOfProceduresStrategy PredicatesByExampleStrategy FunctionsByExampleStrategy - codestrategy
   TellingOfConditionsStrategy - uberstrategy
   ExpandNodes-code - codetarget
   NoticingSyntaxStrategy TellingOfSyntaxStrategy - syntaxstrategy
   ExpandNodes-syntax-interpretation ExpandNodes-code-interpretation - interpretation
   ByExample ByTelling mableNoticingSyntax ByFeedback - nimdimension
 )
(:init 
   (composedOf ExpandNodes-code ExpandNodes-syntax)
   (conceptDimensionInTemplate DefinitionOf t0)
   (conceptDimensionInTemplate DefinitionOf t1)
   (conceptDimensionInTemplate DefinitionOf t2)
   (conceptDimensionInTemplate HowToDo t3)
   (conceptDimensionInTemplate HowToDo t4)
   (conceptDimensionInTemplate HowToDo t5)
   (havePrerequisitesCIs ExpandNodes-syntax)
   (interpretationForTarget ExpandNodes-code-interpretation ExpandNodes-code)
   (interpretationForTarget ExpandNodes-syntax-interpretation ExpandNodes-syntax)
   (nimDimensionInTemplate ByExample t0)
   (nimDimensionInTemplate ByExample t3)
   (nimDimensionInTemplate ByFeedback t2)
   (nimDimensionInTemplate ByFeedback t5)
   (nimDimensionInTemplate mableNoticingSyntax t1)
   (nimDimensionInTemplate mableNoticingSyntax t4)
   (priorInterpretationForTarget ExpandNodes-syntax-interpretation ExpandNodes-syntax)
   (strategyCONCEPTDIMENSION EBEByFeedbackStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION EBELearningStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION ExampleOfProcedureStrategy HowToDo)
   (strategyCONCEPTDIMENSION FunctionsByExampleStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION FunctionsByFeedbackStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ByDefinition)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionWhenToCalculate)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionWhenToDo)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy DefinitionOf)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy HowToDo)
   (strategyCONCEPTDIMENSION PredicatesByExampleStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION PredicatesByFeedbackStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION ProcedureByFeedbackStrategy HowToDo)
   (strategyCONCEPTDIMENSION TellingOfConditionsStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION TellingOfConditionsStrategy ConditionWhenToDo)
   (strategyCONCEPTDIMENSION TellingOfConditionsStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION TellingOfProceduresStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION TellingOfProceduresStrategy HowToDo)
   (strategyCONCEPTDIMENSION TellingOfSyntaxStrategy DefinitionOf)
   (strategyNIMDIMENSION EBEByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION EBELearningStrategy ByExample)
   (strategyNIMDIMENSION ExampleOfProcedureStrategy ByExample)
   (strategyNIMDIMENSION FunctionsByExampleStrategy ByExample)
   (strategyNIMDIMENSION FunctionsByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION NoticingSyntaxStrategy mableNoticingSyntax)
   (strategyNIMDIMENSION PredicatesByExampleStrategy ByExample)
   (strategyNIMDIMENSION PredicatesByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION ProcedureByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION TellingOfConditionsStrategy ByTelling)
   (strategyNIMDIMENSION TellingOfProceduresStrategy ByTelling)
   (strategyNIMDIMENSION TellingOfSyntaxStrategy ByTelling)
   (strategyNeedsPriorCI ProcedureByFeedbackStrategy)
   (strategyRequiresPriorCILearnedByStrategy ProcedureByFeedbackStrategy ExampleOfProcedureStrategy)
   (strategyRequiresPriorCILearnedByStrategy ProcedureByFeedbackStrategy ProcedureByFeedbackStrategy)
   (targetInTemplate ExpandNodes-code t3)
   (targetInTemplate ExpandNodes-code t4)
   (targetInTemplate ExpandNodes-code t5)
   (targetInTemplate ExpandNodes-syntax t0)
   (targetInTemplate ExpandNodes-syntax t1)
   (targetInTemplate ExpandNodes-syntax t2)
   (untried ExampleOfProcedureStrategy ExpandNodes-code ByExample HowToDo)
   (untried ExampleOfProcedureStrategy ExpandNodes-syntax ByExample HowToDo)
   (untried NoticingSyntaxStrategy ExpandNodes-code mableNoticingSyntax HowToDo)
   (untried NoticingSyntaxStrategy ExpandNodes-syntax mableNoticingSyntax HowToDo)
   (untried ProcedureByFeedbackStrategy ExpandNodes-code ByFeedback HowToDo)
   (untried ProcedureByFeedbackStrategy ExpandNodes-syntax ByFeedback HowToDo)
 )
(:goal 
(and (learned ExpandNodes-syntax) (newlyLearned ExpandNodes-syntax) (learned ExpandNodes-code) (newlyLearned ExpandNodes-code))
 )
)
