 (define (problem TBDName)
 (:domain mable-control)
(:objects 
   t3 t2 t1 t0 - template
   SetSegmentFormation-syntax - syntaxtarget
   ByDefinition ConditionWhenToCalculate ConditionEffectsOf HowToDo ConditionWhenTrue HowToCalculate DefinitionOf ConditionWhenToDo - conceptdimension
   PredicatesByFeedbackStrategy EBEByFeedbackStrategy EBELearningStrategy FunctionsByFeedbackStrategy ExampleOfProcedureStrategy ProcedureByFeedbackStrategy TellingOfProceduresStrategy PredicatesByExampleStrategy FunctionsByExampleStrategy - codestrategy
   TellingOfConditionsStrategy - uberstrategy
   SetSegmentFormation-code - codetarget
   NoticingSyntaxStrategy TellingOfSyntaxStrategy - syntaxstrategy
   SetSegmentFormation-code-interpretation SetSegmentFormation-syntax-interpretation - interpretation
   ByExample ByTelling mableNoticingSyntax ByFeedback - nimdimension
 )
(:init 
   (composedOf SetSegmentFormation-code SetSegmentFormation-syntax)
   (conceptDimensionInTemplate DefinitionOf t0)
   (conceptDimensionInTemplate DefinitionOf t1)
   (conceptDimensionInTemplate HowToDo t2)
   (conceptDimensionInTemplate HowToDo t3)
   (havePrerequisitesCIs SetSegmentFormation-syntax)
   (interpretationForTarget SetSegmentFormation-code-interpretation SetSegmentFormation-code)
   (interpretationForTarget SetSegmentFormation-syntax-interpretation SetSegmentFormation-syntax)
   (nimDimensionInTemplate ByTelling t0)
   (nimDimensionInTemplate ByTelling t2)
   (nimDimensionInTemplate mableNoticingSyntax t1)
   (nimDimensionInTemplate mableNoticingSyntax t3)
   (strategyCONCEPTDIMENSION EBEByFeedbackStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION EBELearningStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION ExampleOfProcedureStrategy HowToDo)
   (strategyCONCEPTDIMENSION FunctionsByExampleStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION FunctionsByFeedbackStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ByDefinition)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionWhenToCalculate)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionWhenToDo)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy DefinitionOf)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy HowToDo)
   (strategyCONCEPTDIMENSION PredicatesByExampleStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION PredicatesByFeedbackStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION ProcedureByFeedbackStrategy HowToDo)
   (strategyCONCEPTDIMENSION TellingOfConditionsStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION TellingOfConditionsStrategy ConditionWhenToDo)
   (strategyCONCEPTDIMENSION TellingOfConditionsStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION TellingOfProceduresStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION TellingOfProceduresStrategy HowToDo)
   (strategyCONCEPTDIMENSION TellingOfSyntaxStrategy DefinitionOf)
   (strategyNIMDIMENSION EBEByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION EBELearningStrategy ByExample)
   (strategyNIMDIMENSION ExampleOfProcedureStrategy ByExample)
   (strategyNIMDIMENSION FunctionsByExampleStrategy ByExample)
   (strategyNIMDIMENSION FunctionsByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION NoticingSyntaxStrategy mableNoticingSyntax)
   (strategyNIMDIMENSION PredicatesByExampleStrategy ByExample)
   (strategyNIMDIMENSION PredicatesByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION ProcedureByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION TellingOfConditionsStrategy ByTelling)
   (strategyNIMDIMENSION TellingOfProceduresStrategy ByTelling)
   (strategyNIMDIMENSION TellingOfSyntaxStrategy ByTelling)
   (strategyNeedsPriorCI ProcedureByFeedbackStrategy)
   (strategyRequiresPriorCILearnedByStrategy ProcedureByFeedbackStrategy ExampleOfProcedureStrategy)
   (strategyRequiresPriorCILearnedByStrategy ProcedureByFeedbackStrategy ProcedureByFeedbackStrategy)
   (targetInTemplate SetSegmentFormation-code t2)
   (targetInTemplate SetSegmentFormation-code t3)
   (targetInTemplate SetSegmentFormation-syntax t0)
   (targetInTemplate SetSegmentFormation-syntax t1)
   (untried NoticingSyntaxStrategy SetSegmentFormation-code mableNoticingSyntax DefinitionOf)
   (untried NoticingSyntaxStrategy SetSegmentFormation-code mableNoticingSyntax HowToDo)
   (untried NoticingSyntaxStrategy SetSegmentFormation-syntax mableNoticingSyntax DefinitionOf)
   (untried NoticingSyntaxStrategy SetSegmentFormation-syntax mableNoticingSyntax HowToDo)
   (untried TellingOfProceduresStrategy SetSegmentFormation-code ByTelling HowToDo)
   (untried TellingOfProceduresStrategy SetSegmentFormation-syntax ByTelling HowToDo)
   (untried TellingOfSyntaxStrategy SetSegmentFormation-code ByTelling DefinitionOf)
   (untried TellingOfSyntaxStrategy SetSegmentFormation-syntax ByTelling DefinitionOf)
 )
(:goal 
(and (learned SetSegmentFormation-syntax) (newlyLearned SetSegmentFormation-syntax) (learned SetSegmentFormation-code) (newlyLearned SetSegmentFormation-code))
 )
 )