 (define (problem TBDName)
 (:domain mable-control)
(:objects 
   t2 t1 t0 - template
   AnnotateSegment-syntax SetCompanySegmentTraversalTime-syntax - syntaxtarget
   ByDefinition ConditionWhenToCalculate ConditionEffectsOf HowToDo ConditionWhenTrue HowToCalculate DefinitionOf ConditionWhenToDo - conceptdimension
   PredicatesByFeedbackStrategy EBEByFeedbackStrategy EBELearningStrategy FunctionsByFeedbackStrategy ExampleOfProcedureStrategy ProcedureByFeedbackStrategy TellingOfProceduresStrategy PredicatesByExampleStrategy FunctionsByExampleStrategy - codestrategy
   TellingOfConditionsStrategy - uberstrategy
   SetAllSegmentTraversalTime-code SetAllSegmentTraversalTime-syntax - codetarget
   NoticingSyntaxStrategy TellingOfSyntaxStrategy - syntaxstrategy
   SetAllSegmentTraversalTime-syntax-interpretation SetAllSegmentTraversalTime-code-interpretation AnnotateSegment-syntax-interpretation SetCompanySegmentTraversalTime-syntax-interpretation - interpretation
   ByExample ByTelling mableNoticingSyntax ByFeedback - nimdimension
 )
(:init 
   (composedOf SetAllSegmentTraversalTime-code SetAllSegmentTraversalTime-syntax)
   (conceptDimensionInTemplate DefinitionOf t0)
   (conceptDimensionInTemplate DefinitionOf t1)
   (conceptDimensionInTemplate DefinitionOf t2)
   (havePrerequisitesCIs AnnotateSegment-syntax)
   (havePrerequisitesCIs SetCompanySegmentTraversalTime-syntax)
   (interpretationForTarget AnnotateSegment-syntax-interpretation AnnotateSegment-syntax)
   (interpretationForTarget SetAllSegmentTraversalTime-code-interpretation SetAllSegmentTraversalTime-code)
   (interpretationForTarget SetCompanySegmentTraversalTime-syntax-interpretation SetCompanySegmentTraversalTime-syntax)
   (nimDimensionInTemplate mableNoticingSyntax t0)
   (nimDimensionInTemplate mableNoticingSyntax t1)
   (nimDimensionInTemplate mableNoticingSyntax t2)
   (priorInterpretationForTarget SetAllSegmentTraversalTime-syntax-interpretation SetAllSegmentTraversalTime-syntax)
   (strategyCONCEPTDIMENSION EBEByFeedbackStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION EBELearningStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION ExampleOfProcedureStrategy HowToDo)
   (strategyCONCEPTDIMENSION FunctionsByExampleStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION FunctionsByFeedbackStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ByDefinition)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionWhenToCalculate)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionWhenToDo)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy DefinitionOf)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION NoticingSyntaxStrategy HowToDo)
   (strategyCONCEPTDIMENSION PredicatesByExampleStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION PredicatesByFeedbackStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION ProcedureByFeedbackStrategy HowToDo)
   (strategyCONCEPTDIMENSION TellingOfConditionsStrategy ConditionEffectsOf)
   (strategyCONCEPTDIMENSION TellingOfConditionsStrategy ConditionWhenToDo)
   (strategyCONCEPTDIMENSION TellingOfConditionsStrategy ConditionWhenTrue)
   (strategyCONCEPTDIMENSION TellingOfProceduresStrategy HowToCalculate)
   (strategyCONCEPTDIMENSION TellingOfProceduresStrategy HowToDo)
   (strategyCONCEPTDIMENSION TellingOfSyntaxStrategy DefinitionOf)
   (strategyNIMDIMENSION EBEByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION EBELearningStrategy ByExample)
   (strategyNIMDIMENSION ExampleOfProcedureStrategy ByExample)
   (strategyNIMDIMENSION FunctionsByExampleStrategy ByExample)
   (strategyNIMDIMENSION FunctionsByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION NoticingSyntaxStrategy mableNoticingSyntax)
   (strategyNIMDIMENSION PredicatesByExampleStrategy ByExample)
   (strategyNIMDIMENSION PredicatesByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION ProcedureByFeedbackStrategy ByFeedback)
   (strategyNIMDIMENSION TellingOfConditionsStrategy ByTelling)
   (strategyNIMDIMENSION TellingOfProceduresStrategy ByTelling)
   (strategyNIMDIMENSION TellingOfSyntaxStrategy ByTelling)
   (strategyRequiresPriorCILearnedByStrategy ProcedureByFeedbackStrategy ExampleOfProcedureStrategy)
   (templateIncludesPriorInterpretationByStrategy t0 ExampleOfProcedureStrategy)
   (strategyNeedsPriorCI ProcedureByFeedbackStrategy)
   (strategyRequiresPriorCILearnedByStrategy ProcedureByFeedbackStrategy ProcedureByFeedbackStrategy)
   (targetInTemplate AnnotateSegment-syntax t1)
   (targetInTemplate SetAllSegmentTraversalTime-code t0)
   (targetInTemplate SetCompanySegmentTraversalTime-syntax t2)
   (untried NoticingSyntaxStrategy AnnotateSegment-syntax mableNoticingSyntax DefinitionOf)
   (untried NoticingSyntaxStrategy SetCompanySegmentTraversalTime-syntax mableNoticingSyntax DefinitionOf)
 )
(:goal 
(and (learned SetAllSegmentTraversalTime-code) (newlyLearned SetAllSegmentTraversalTime-code) (learned AnnotateSegment-syntax) (newlyLearned AnnotateSegment-syntax) (learned SetCompanySegmentTraversalTime-syntax) (newlyLearned SetCompanySegmentTraversalTime-syntax))
 )
)